workflows:
  ios-debug-build:
    name: iOS Debug Build - ChallengeMe
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Flutter doctor
        script: |
          flutter doctor -v
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Generate iOS config
        script: |
          flutter precache --ios
          flutter build ios --config-only --no-codesign
      
      - name: Clean Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod cache clean --all
          cd ..
      
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..
      
      - name: Build iOS (debug, no sign)
        script: |
          flutter build ios --debug --no-codesign --verbose
      
      - name: Create archive
        script: |
          cd build/ios/iphoneos
          if [ -d "Runner.app" ]; then
            zip -r ChallengeMe.zip Runner.app
            mv ChallengeMe.zip ../../../
          else
            echo "Runner.app not found!"
            exit 1
          fi
    
    artifacts:
      - ChallengeMe.zip
      - build/ios/iphoneos/Runner.app
    
    publishing:
      email:
        recipients:
          - junioryovo2002@gmail.com
        notify:
          success: true
          failure: true
