workflows:
  ios-debug-build:
    name: iOS Debug Build - ChallengeMe
    max_build_duration: 90
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 15.3 # Version plus récente pour Swift 6
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.demo"
    scripts:
      - name: Set Flutter version
        script: |
          flutter --version
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Generate iOS config files
        script: |
          flutter precache --ios
          flutter build ios --config-only --no-codesign
      
      - name: Clean iOS build cache
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks DerivedData
          pod cache clean --all
          cd ..
      
      - name: Update CocoaPods repo
        script: |
          pod repo update
      
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose
          cd ..
      
      - name: Build iOS app (debug, no signing)
        script: |
          flutter build ios --debug --no-codesign --verbose
      
      - name: Create .app archive
        script: |
          cd build/ios/iphoneos
          if [ -d "Runner.app" ]; then
            zip -r ChallengeMe-debug.zip Runner.app
            mv ChallengeMe-debug.zip ../../../
            echo "✅ Archive created successfully"
          else
            echo "❌ Runner.app not found"
            exit 1
          fi
    
    artifacts:
      - ChallengeMe-debug.zip
      - build/ios/iphoneos/Runner.app
      - ios/Pods/Manifest.lock
    
    publishing:
      email:
        recipients:
          - junioryovo2002@gmail.com
        notify:
          success: true
          failure: true
