workflows:
  ios-app-workflow:
    name: iOS .app Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 15.0
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Generate iOS config (IMPORTANT)
        script: |
          flutter precache --ios
          flutter build ios --config-only --no-codesign
      
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      
      - name: Flutter build iOS debug
        script: |
          flutter build ios --debug --no-codesign
      
      - name: Zip .app for download
        script: |
          cd build/ios/iphoneos
          zip -r Runner.zip Runner.app
          mv Runner.zip ../../
    
    artifacts:
      - build/Runner.zip
      - build/ios/iphoneos/Runner.app
    
    publishing:
      email:
        recipients:
          - junioryovo2002@gmail.com
        notify:
          success: true
