// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzD0oXFSZwOWlD4l6oizsGL05dBCRCeo',
    appId: '1:481078420265:web:8a335414368474bb88cd38',
    messagingSenderId: '481078420265',
    projectId: 'challengeme-7689a',
    authDomain: 'challengeme-7689a.firebaseapp.com',
    storageBucket: 'challengeme-7689a.firebasestorage.app',
    measurementId: 'G-ZH0MG0CQZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL4oEO4VADnFZzuIPKIHxtIZdaMmz86Og',
    appId: '1:481078420265:android:9b14f6079d8cef7288cd38',
    messagingSenderId: '481078420265',
    projectId: 'challengeme-7689a',
    storageBucket: 'challengeme-7689a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWqaMUpaKuuyqu0y_qRdxFVW_uycTPUM',
    appId: '1:481078420265:ios:7af9fd71cf60271088cd38',
    messagingSenderId: '481078420265',
    projectId: 'challengeme-7689a',
    storageBucket: 'challengeme-7689a.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWqaMUpaKuuyqu0y_qRdxFVW_uycTPUM',
    appId: '1:481078420265:ios:7af9fd71cf60271088cd38',
    messagingSenderId: '481078420265',
    projectId: 'challengeme-7689a',
    storageBucket: 'challengeme-7689a.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPzD0oXFSZwOWlD4l6oizsGL05dBCRCeo',
    appId: '1:481078420265:web:b0f4516337ff9d1e88cd38',
    messagingSenderId: '481078420265',
    projectId: 'challengeme-7689a',
    authDomain: 'challengeme-7689a.firebaseapp.com',
    storageBucket: 'challengeme-7689a.firebasestorage.app',
    measurementId: 'G-8FMN2YH3RW',
  );
}
